import type { DailyGoalProgress, DailyGoalSettings, ReviewStreakState } from "@/services/goals";
import type { ReviewReminderSettings } from "@/services/notifications";
import type { ThemeMode } from "@/theme/types";

export type SettingsScreenProps = {
    onLogout: () => void;
    canLogout: boolean;
    isGuest: boolean;
    onRequestLogin: () => void;
    onRequestSignUp: () => void;
    onShowOnboarding: () => void;
    appVersion: string;
    profileDisplayName: string | null;
    profileUsername: string | null;
    onNavigateNickname: () => void;
    onNavigatePassword: () => void;
    onNavigateAccountDeletion: () => void;
    onExportBackup: (passphrase: string) => Promise<void>;
    onImportBackup: (passphrase: string) => Promise<void>;
    themeMode: ThemeMode;
    fontScale: number;
    onNavigateThemeSettings: () => void;
    onNavigateFontSettings: () => void;
    dailyGoalSettings: DailyGoalSettings;
    dailyGoalProgress: DailyGoalProgress;
    reviewStreak: ReviewStreakState;
    reviewReminderSettings: ReviewReminderSettings;
    nextReminderLabel: string | null;
    onToggleDailyGoal: (enabled: boolean) => void;
    onSelectDailyGoalTarget: (targetCount: number) => void;
    onToggleReviewReminder: (enabled: boolean) => void;
    onSelectReviewReminderTime: (hour: number, minute: number) => void;
    onToggleReviewReminderWeekday: (weekday: number) => void;
};
